Repository privacytools/privacytools.io, pull requests merged in 2019-08, with the labels that each got.

#1072 Add Tor URL to VPN Provider website column
  _includes/sections/email-providers.html
  _includes/sections/vpn.html
Labels: Tor, VPN, ✨ enhancement

#1083 Update logos
  assets/img/provider/StartMail.png
  assets/img/provider/StartPage.png
  assets/img/tools/F-Droid.png
  assets/img/tools/Purism.png
  assets/img/tools/Thunderbird.png
  assets/img/tools/Tor-Browser.png
Labels: 🏠 housekeeping

#1085 Center icons correctly in share buttons
  _includes/footer.html
Labels: 🌐 website issue, 🏠 housekeeping

#1063 instant-messenger: correct supported platforms of Gajim
  _includes/sections/instant-messenger.html
Labels: 🌐 website issue

#1047 instant-messengers: delist Riot
  _includes/sections/instant-messenger.html
  source_code.md
Labels: ❌ software removal, 🆘 critical, 🌐 website issue

#1084 Add Onion service URLs for cryptostorm and ExpressVPN
  _includes/sections/vpn.html
Labels: ✨ enhancement, 🔒 vpn

#1090 Add warnings to VPN section, encourage Tor use
  pages/providers/vpn.html
Labels: tor, 🔒 vpn

#1079 Highlight first columns in Email and VPN tables and consolidate column names
  _includes/sections/email-providers.html
  _includes/sections/vpn.html
Labels: ✨ enhancement, 📧 email, 🔒 vpn

#1073 Update discussion issue template to direct new discussions to the forum
  .github/ISSUE_TEMPLATE/3_Discussion.md
Labels: feedback wanted, 💬 discussion

#1092 Remove Subgraph OS
  _includes/sections/operating-systems.html
  source_code.md
Labels: os, ❌ software removal

#1094 Replace "Yes" with "Accepted", which was used in other rows
  _includes/sections/email-providers.html
Labels: 🌐 website issue, 📧 email

#1099 Change "E2EE encryption" to "E2E encryption"
  _includes/sections/notebooks.html
Labels: 🌐 website issue

#1108 Add link to Calendar/Contacts Sync Tools page to navbar
  _includes/nav.html
Labels: 🌐 website issue

#1114 fix icon for Snowflake git service
  _includes/sections/browser-addons.html
Labels: ⚙️ web extensions, 🌐 website issue

#1103 Remove cryptostorm
  _includes/sections/vpn.html
  assets/img/provider/Cryptostorm.png
Labels: ❌ software removal, 🔒 vpn

#1041 Add Checklist to PRs
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 🏠 housekeeping

#1097 Add Encrypted DNS providers table
  _includes/sections/dns.html
  source_code.md
Labels: ✨ enhancement, 🗄️ dns

#1120 Add Social News Aggregators to source_code.md
  source_code.md
Labels: 🐛 bug

#1121 Add Soverin to Email Providers table
  _includes/sections/email-providers.html
  assets/img/provider/Soverin.png
Labels: 🆕 software suggestion, 📧 email

#1127 browser-tweaks: document TRR/DoH
  _includes/sections/browser-tweaks.html
Labels: 🗄️ dns, 🦊 firefox

#1122 Remove duplicate "Social Networks" in navbar
  _includes/nav.html
Labels: 🌐 website issue

#1129 Conditionally add top padding to Android addons icons
  _includes/sections/android-addons.html
  assets/css/style.scss
Labels: 🌐 website issue, 🤖 android

#1067 Add Team chat section
  _includes/nav.html
  _includes/sections/teamchat.html
  assets/img/tools/keybase.png
  assets/img/tools/rocket.chat.png
  pages/software/teamchat.html
  source_code.md
Labels: wip

#1128 Remove XPrivacyLua
  _includes/sections/android-addons.html
  source_code.md
Labels: ❌ software removal, 🤖 android

#1145 Update Qubes OS Tor link
  _includes/sections/operating-systems.html
Labels: tor, 🌐 website issue

#1141 Remove VPN.ht
  _includes/sections/vpn.html
Labels: high priority, 🔒 vpn

#1148 Convert operating systems to cardv2.html
  _includes/cardv2.html
  _includes/sections/live-operating-systems.html
  _includes/sections/mobile-operating-systems.html
  _includes/sections/operating-systems.html
  _includes/sections/router-firmware.html
Labels: os, 🏠 housekeeping

#1149 Small Improvements
  _includes/cardv2.html
  _includes/nav.html
  _includes/sections/browser-addons.html
  _includes/sections/browser-recommendation.html
Labels: 🌐 website issue, 🏠 housekeeping, 👁️ browsers

#1155 Remove some providers
  _includes/sections/vpn.html
  assets/img/provider/AirVPN.png
  assets/img/provider/AzireVPN.png
  assets/img/provider/EarthVPN.png
  assets/img/provider/ExpressVPN.png
  assets/img/provider/FrootVPN.png
  assets/img/provider/Perfect-Privacy.png
  assets/img/provider/Proxy.sh.png
  assets/img/provider/Trust.Zone.png
  assets/img/provider/VPN.ht.png
  assets/img/provider/VPNTunnel.png
  assets/img/provider/blackVPN.png
  assets/img/provider/hide.me.png
  assets/img/provider/ovpn.png
  assets/img/provider/vpnarea.png
Labels: 🔒 vpn

#1161 Remove Flock
  _includes/sections/calendar-contacts-sync.html
Labels: 🏠 housekeeping

#1135 Delist Ricochet
  _includes/sections/instant-messenger.html
  source_code.md
Labels: ❌ software removal

#1143 Update Email column sorting
  _includes/sections/email-providers.html
Labels: 🌐 website issue, 📧 email

#1160 Update Disroot's mailbox size
  _includes/sections/email-providers.html
Labels: 🌐 website issue, 📧 email

#1164 Combine "worth mentioning" sections in DNS page
  _includes/sections/dns.html
Labels: ✨ enhancement, 🗄️ dns

#1168 Add Hat.sh to File Encryption page
  _includes/sections/file-encryption.html
  source_code.md
Labels: 🆕 software suggestion, 🔒 file encryption

#1166 Update links in "More VPN Providers"
  _includes/sections/vpn.html
Labels: ✨ enhancement, 🔒 vpn

#1156 Replace Trisquel with Fedora
  _includes/sections/operating-systems.html
  assets/img/tools/Fedora.png
  assets/img/tools/Trisquel.png
Labels: os

#1170 Update Password Managers page to cardv2
  _includes/sections/password-managers.html
  assets/img/tools/KeePass.png
  assets/img/tools/keepassxc.png
  source_code.md
Labels: ✨ enhancement, 🔐 password managers

#1171 Fix Hat.sh link
  _includes/sections/file-encryption.html
Labels: 🌐 website issue, 🔒 file encryption

#1174 Reworked VPN Providers
  _includes/sections/vpn.html
  assets/img/provider/NordVPN.png
  pages/providers/vpn.html
Labels: 🔒 vpn

#1172 Update Wire's metadata warning to increase clarity
  _includes/cardv2.html
  _includes/sections/instant-messenger.html
Labels: ✨ enhancement, 🗨️ instant messaging (im)

#1169 Remove Brave
  _includes/sections/browser-recommendation.html
  assets/img/tools/Brave.png
  source_code.md
Labels: ❌ software removal, 👁️ browsers

#1179 Update small PR template typo
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 🏠 housekeeping

#1178 Indicate which DNS providers support DoT over port 443
  _includes/sections/dns.html
Labels: ✨ enhancement, 🗄️ dns

#1154 [WIP] Rewrite navbar
  _includes/nav.html
  _includes/scripts.html
  assets/css/style.scss
  assets/js/main.js
Labels: wip, 🌐 website issue

#1203 Fix tooltips
  _includes/scripts.html
  assets/js/main.js
Labels: 🌐 website issue, 🏠 housekeeping

#1200 DNS: add Nebulo as worth mentioning & warn about DoH metadata & sort worth mentioning/additional information into sublists
  _includes/sections/dns.html
  source_code.md
Labels: ios, 🗄️ dns, 🤖 android

#1209 Remove translation with broken TLS
  _includes/nav.html
Labels: 🏠 housekeeping

#1210 Remove white backgrounds, update and remove (not used) images
  _includes/sections/browser-fingerprint.html
  _includes/sections/cloud-storage.html
  _includes/sections/search-engines.html
  _includes/sections/windows10.html
  assets/img/addons/Disconnect.png
  assets/img/addons/Orbot.png
  assets/img/addons/Self-Destructing-Cookies.png
  assets/img/addons/netguard.png
  assets/img/addons/ublock.png
  assets/img/addons/xprivacylua.png
  assets/img/icons/github.png
  assets/img/icons/reddit.png
  assets/img/icons/twitter.png
  assets/img/layout/UKUSA.png
  assets/img/layout/Windows-10-Privacy.jpg
  assets/img/layout/Windows-10-Privacy.png
  assets/img/layout/browser-fingerprint.jpg
  assets/img/layout/browser-fingerprint.png
  assets/img/layout/git.png
  assets/img/layout/kopimi.png
  assets/img/layout/tor.png
  assets/img/layout/www.png
  assets/img/provider/DuckDuckGo.jpg
  assets/img/provider/DuckDuckGo.png
  assets/img/provider/Nextcloud.png
  assets/img/provider/Qwant.png
  assets/img/provider/RuggedInbox.png
  assets/img/provider/S4.jpg
  assets/img/provider/S4.png
  assets/img/provider/StartMail.png
  assets/img/provider/StartPage.png
  assets/img/provider/disroot.org.png
  assets/img/provider/gnu-social.png
  assets/img/provider/qwant.jpg
  assets/img/provider/searx.jpg
  assets/img/provider/searx.png
  assets/img/tools/CopperheadOS.png
  assets/img/tools/Debian.png
  assets/img/tools/Etherpad.png
  assets/img/tools/GnuPG.png
  assets/img/tools/LessPass.png
  assets/img/tools/LibreCMC.png
  assets/img/tools/LibreWRT.png
  assets/img/tools/Magic-Wormhole.png
  assets/img/tools/Mumble.png
  assets/img/tools/PrivateBin.png
  assets/img/tools/Purism.png
  assets/img/tools/Ricochet.png
  assets/img/tools/Riot.png
  assets/img/tools/Sailfish-OS.png
  assets/img/tools/Tor-Project.png
  assets/img/tools/VeraCrypt.png
  assets/img/tools/WriteAs.png
  assets/img/tools/keybase.png
  assets/img/tools/pfSense.png
  assets/img/tools/wire.png
Labels: 🏠 housekeeping

#1176 Add section to validate DNS connection
  _includes/sections/dns.html
Labels: ✨ enhancement, 🗄️ dns

#1205 privacy-resources: sort information, fix cloudflare-tor link & move it to information
  _includes/sections/privacy-resources.html
Labels: 🌐 website issue

#1213 Make JavaScript work with LibreJS
  _includes/footer.html
  _includes/scripts.html
  about/javascript/index.html
  assets/js/main.js
Labels: 🏠 housekeeping

#1217 about:config: delete geo.enabled
  _includes/sections/browser-tweaks.html
Labels: 🏠 housekeeping, 🦊 firefox

#1220 dns: document enabling Firefox TRR
  _includes/sections/browser-tweaks.html
  _includes/sections/dns.html
Labels: 🗄️ dns, 🦊 firefox

#1222 Remove text wrapping for DNS providers table server locations column
  _includes/sections/dns.html
  assets/css/style.scss
Labels: ✨ enhancement, 🗄️ dns

#1226 Add NixNet DNS
  _includes/sections/dns.html
  source_code.md
Labels: 🗄️ dns

#1235 Center table row values
  assets/css/style.scss
Labels: ✨ enhancement, 📧 email, 🗄️ dns

#1236 Fix DNS table, it did contain text under it
  _includes/sections/dns.html
Labels: 🌐 website issue

#1204 Add dark theme
  _includes/head.html
  _includes/nav.html
  assets/css/dark.scss
  assets/css/style.scss
  assets/js/main.js
Labels: ✨ enhancement

#1238 Fix LessPass GitHub link
  _includes/sections/password-managers.html
Labels: 🌐 website issue

#1231 operating-systems.html: add a warning for Linux/CPU vulns
  _includes/sections/operating-systems.html
Labels: os, 💬 discussion, 💻 hardware
