Repository privacytools/privacytools.io, pull requests merged in 2019-07, with the labels that each got.

#1001 Add Security Policy
  .well-known/security.txt
  SECURITY.md
Labels: feedback wanted

#1024 instant-messenger: add privacy concerns warning to Riot
  _includes/sections/instant-messenger.html
Labels: critical

#1054 dns: add ICANN DNS supporting encryption to worth mentioning
  _includes/sections/dns.html
Labels: Firefox
