Repository privacytools/privacytools.io, pull requests merged in 2020-01, with the labels that each got.

#1651 Request issue/PR opener to disclose their connection to the software, why they are suggesting it and keep us up-to-date
  .github/ISSUE_TEMPLATE/1_Software_Suggestion.md
  .github/ISSUE_TEMPLATE/2_Software_Removal.md
  .github/ISSUE_TEMPLATE/7_DNS_provider.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: high priority, ✨ enhancement

#1603 Change a warning of Firefox about:config entering
  _includes/sections/browser-tweaks.html
Labels: WIP, ℹ️ help wanted, 🔎 research required, 🦊 Firefox

#1654 Update Edward Snowden quotes from Permanent Record
  _includes/sections/quotes.html
Labels: ✨ enhancement
